### PR TITLE
fix: do not `panic` if remote env is not buildable

### LINKED ISSUE #948: `flox activate -r` panics if the environment cannot be built
@ysndr I get a weird error out of flox on this

`Version: 0.3.6-283-ge4618f1`

image

_Originally posted by @ghudgins in https://github.com/flox/flox/issues/824#issuecomment-1930369536_

### PR DESCRIPTION
**Pull request by ysndr**
fixes #948

### CODE REVIEW

File: cli/flox-rust-sdk/src/models/environment/remote_environment.rs [hunk 1]
```diff
@@ -48,6 +48,9 @@ pub enum RemoteEnvironmentError {
 
     #[error("could not create temporary environment")]
     CreateTempDotFlox(#[source] std::io::Error),
+
+    #[error("could not update out link ({1})")]
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/models/environment/remote_environment.rs:52]: Suggestion: if this message could end up user-facing it probably needs to have a description that would be meaningful to a user.

File: cli/flox-rust-sdk/src/models/environment/remote_environment.rs [hunk 2]
```diff
@@ -58,6 +61,8 @@ pub struct RemoteEnvironment {
 
 impl RemoteEnvironment {
     /// Pull a remote environment into a provided (temporary) managed environment
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/models/environment/remote_environment.rs:63]:
```suggestion
    /// Pull a remote environment into a provided (temporary) managed environment.
```

File: cli/flox-rust-sdk/src/models/environment/remote_environment.rs [hunk 3]
```diff
@@ -58,6 +61,8 @@ pub struct RemoteEnvironment {
...
+    /// Constructiing a [RemoteEnvironment] _does not_ create a gc-root
+    /// or guarantee that the environment is valid
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/models/environment/remote_environment.rs:65]:
```suggestion
    /// or guarantee that the environment is valid.
```

**Review by zmitchell — CHANGES_REQUESTED** [review]

File: cli/flox-rust-sdk/src/models/environment/remote_environment.rs (hunk 1 above)
Comment (ysndr) [reply cli/flox-rust-sdk/src/models/environment/remote_environment.rs:52]: We have conversions into user friendly errors in the errors module, I didnt write one for this variant (i just pass this through) because i think this error woule rather be a bug than anything a user needs to deal with. I guess we need some sort of tag somewhere what is but and what not but wither way these errors are more dev/us focused IMO.

**Review by zmitchell — APPROVED** [review]

**Review by zmitchell — APPROVED** [review]
