### PR TITLE
fix: respect original priority for propagated packages

### LINKED ISSUE #2958: pr
**Describe the bug:**

**Steps to reproduce:**
1.
```toml
version = 1
[install]
python313.pkg-path = "python313"
pre-commit.pkg-path = "pre-commit"
pre-commit.priority = 8
```
2. `flox activate`
3.
```shell
$ ls -alh $FLOX_ENV/bin/python
lrwxrwxrwx 1 root root 69 Dec 31  1969 /home/tom/flox/office/pre-commit/.flox/run/x86_64-linux.pre-commit.dev/bin/python -> /nix/store/f2krmq3iv5nibcvn4rw7nrnrciqprdkh-python3-3.12.9/bin/python
```

Result:
Shows the pre-commit's python won, despite being given a lower priority.

Expected:
python313 should win

1.3.17-g0005cbc

Notes:

This is due to this line when processing propagated packages
https://github.com/flox/flox/blob/3ec390b22289596ec954541f048b50ca63b3e105/buildenv/builder.pl#L640
> my $priorityCounter = 1000; # don't care about collisions
But this might need to be either `5000` or `originalPriority * 1000` in order for the prioritization to work as expected. Tested that this does solve it, though would need to double check the original intent.

Workaround is to set the priority of python313 to 1 such that it has 1 * 1000 later on:
```toml
version = 1
[install]
python313.pkg-path = "python313"
python313.priority = 1
pre-commit.pkg-path = "pre-commit"
```

### PR DESCRIPTION
**Pull request by limeytexan**
## Proposed Changes

Issue #2958 documents the issue of the priority of propagated packages not following the priority of the packages included within the manifest's `[install]` block. This patch addresses this by updating the priority of propagated packages to be a multiple of the "base" package's original priority, while at the same time using a counter to prevent collisions amongst propagated packages as was implemented by the nixpkgs buildenv upstream.
    
Also re-enables the priority integration test in edit.bats.
    
Closes #2958.

## Release Notes

* Addresses issue assigning the correct priority of propagated packages within Flox environments activated in "develop" mode.

### CODE REVIEW

**Comment by limeytexan** [comment]
Regarding [the failing test](https://github.com/flox/flox/actions/runs/24010302903/job/70020706097?pr=4149), works on my machine? Will try to re-run it to see if it's a flakey test.
```
flox [tmp limeytexan/default] Michaels-MBP-3:flox-rust-sdk brantley$ RUST_LOG=debug cargo test -- providers::build::tests::boost_include_only_sandbox_pure --show-output 
+ command cargo test -- providers::build::tests::boost_include_only_sandbox_pure --show-output
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.17s
     Running unittests src/lib.rs (/private/tmp/myflox/target/debug/deps/flox_rust_sdk-d70ca2f4537c7222)

running 1 test
test providers::build::tests::boost_include_only_sandbox_pure ... ok

successes:

successes:
    providers::build::tests::boost_include_only_sandbox_pure

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 464 filtered out; finished in 3.19s

   Doc-tests flox_rust_sdk
──
running 0 tests

successes:

successes:

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.00s
```

**Comment by limeytexan** [comment]
Confirmed a few things about priority in `builder.pl`.

By convention:

* we honour collisions for priorities < 1000
* we ignore collisions for priorities >= 1000
* we do this by incrementing a priority counter whenever we assign any priority over 1000, so that all assignments over 1000 are unique

We were mistakenly assigning all of our packages up in the (1000 * priority) range, even when they were packages (and outputs) found in the install block.

As a reminder, the higher the priority number, the lower its precedence - in other words "priority 1" beats everything.

Updating the logic accordingly.

File: buildenv/builder.pl [hunk 1]
```diff
@@ -530,15 +532,17 @@ sub addPkg {
...
 
-                    # Add other outputs with incrementing priority
+                    # Add other outputs with incremented priority so that they do not trigger
+                    # collision failures but will have lower precedence than other installed
+                    # packages in case of collisions.
                     foreach my $otherPath (@otherOutputPaths) {
                         push @retarray, {
                             "paths" => [ $otherPath ],
-                            "priority" => ((1000 * $package->{"priority"}) + $otherOutputPriorityCounter++)
+                            "priority" => ((1000 * $package->{"priority"}) + $ignoreCollisionCounter++)
```
Comment (gilmishal) [inline buildenv/builder.pl:566]: Does this mean that explicitly defined outputs on v1.9+ manifest will have a higher priority, and might be overridden by a propagated dependency?

**Review by gilmishal — APPROVED** [review]

File: buildenv/builder.pl (hunk 1 above)
Comment (limeytexan) [reply buildenv/builder.pl:566]: This bit of logic is included within a block guarded by the following condition:
```perl
                if (exists $manifest->{"version"} && $manifest->{"version"} == 1) {
```

So no, a packages' outputs as listed in a v2+ manifest (i.e. one containing a `schema-version` attribute) will be parsed with the priorities directly as specified in the manifest.

**Comment by limeytexan** [comment]
Discussed with @gilmishal the idea of a simpler implementation for that test:

```
% flox list -c
version = 1

[build]
foo.command = """
  mkdir -p $out/bin
  echo "echo FAIL && false" > $out/bin/collide
  chmod +x $out/bin/collide
"""

bar.command = """
  mkdir -p $out/bin $out/nix-support
  echo "echo SUCCESS && true" > $out/bin/collide
  chmod +x $out/bin/collide
  echo ${foo} > $out/nix-support/propagated-build-inputs
"""
% flox build bar
% flox init -d <tempdir>
% flox install -d <tempdir> $(readlink result-bar)
% flox activate -d <tempdir> -m dev -- collide
```

If that final command returns true then the test passes, else it fails. (Notably, this test fails for the currently-released Flox!)

I think we can include this entire logic within `edit.bats` and avoid having to create a Nix expression.

**Comment by limeytexan** [comment]
Re-ran the flakey test and it passed for a second time with commit b09c09f1738ce12ce17817b8545ab480b4ea7ea9 in the PR. Would like to get to the bottom of this, but I'm confident the PR is good and it's the test that's flakey here.

**Comment by limeytexan** [comment]
> Re-ran the flakey test and it passed for a second time with commit b09c09f1738ce12ce17817b8545ab480b4ea7ea9 in the PR. Would like to get to the bottom of this, but I'm confident the PR is good and it's the test that's flakey here.

Well, found the reason for the flakey test, and it's a problem that is hidden by the fact we bury STDERR from the buildEnv invocation when rendering environments. When I split out the command and run it by hand I can see a warning about the use of `each`:
```
environment> ⚠️ WARNING: Use of each() on hash after insertion without resetting hash iterator results in undefined behavior, Perl interpreter: 0x100729c00 at /nix/store/3xxr017kpypdn51f7cfj8wryjhhcsi8j-flox-buildenv-0.0.1/lib/builder.pl line 760.
```

Fortunately we can address the warning by switching back to `foreach`.

I was also able to confirm that this fixed the issue by creating a reproducer that allowed me to precisely pin down the test. My reproducer was the following invocation:
```
nix --option extra-experimental-features 'nix-command flakes' --option pure-eval false --print-build-logs build --no-link --offline --json --file ~/src/myflox-PR4149/result-buildenv/lib/buildenv.nix --argstr manifestLock /tmp/manifest.lock
```

... and when I added an extra `"manifest.hook": {}` line to the `manifest.lock` file it would cause a different package to be linked into the resulting environment. I then confirmed that with the `foreach` approach this problem did not occur, and that then gave me a reproducible result with which to confirm that we did in fact need to add `gcc-unwrapped.lib` to the list of `runtime-packages` for this test to pass.
