### PR TITLE
fix: set MANPATH with respect to the existing and default manpath

### LINKED ISSUE #684: Setting MANPATH on activation removes ability to see man pages for system tools
**Describe the bug:**

I can't `man` things that are system provided when I have an activated environment. 

**Steps to reproduce:**
1. `echo $MANPATH`
1. `man uptime` # note this works
1. `flox activate` 
1. `man uptime` # no manual entry found for uptime
1. `echo $MANPATH`

Result: 

```
flox [default] [0] stahnma@floxbox01 ~ № man uptime
No manual entry for uptime
```

Expected: 

The man page is displayed. 

**Screenshots/terminal output (if relevant):**

```
[0] stahnma@floxbox01 ~ № echo $MANPATH

[0] stahnma@floxbox01 ~ № man uptime
[0] stahnma@floxbox01 ~ № flox activate
Welcome to your flox environment!
flox [default] [0] stahnma@floxbox01 ~ № man uptime
No manual entry for uptime
flox [default] [1] stahnma@floxbox01 ~ №
```

** flox Version (run `flox --version` if possible): **

Version: 0.3.6-168-g2d8d41c 

On Darwin, with system provided bash as shell. 

Cursor_and_floxbox01

### PR DESCRIPTION
**Pull request by ysndr**
1) If MANPATH begins with a colon, it is appended to the default list; 
2) if it ends with a colon, it is prepended to the default list; 
3) or if it contains two adjacent colons, the standard search path is inserted between the colons. 
4) If none of these conditions are met, it overrides the standard search path.

We're making use of rule 2) here

fixes #684

### CODE REVIEW

**Review by mkenigs — DISMISSED** [review]
suggestion blocking: respect the behavior of existing `MANPATH`. If e.g. `MANPATH` is currently set to have no colons, shouldn't we just prepend, but not add the trailing colon? Or do we not care about handling those cases?

**Review by aakropotkin — APPROVED** [review]

File: pkgdb/src/buildenv/assets/etc/profile.d/0100_common-paths.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@
 PATH="$FLOX_ENV/bin:$FLOX_ENV/sbin${PATH:+:$PATH}"
 FPATH="$FLOX_ENV/share/zsh/vendor-completions${FPATH:+:$FPATH}"
 FPATH="$FLOX_ENV/share/zsh/site-functions:$FPATH"
-MANPATH="$FLOX_ENV/share/man${MANPATH:+:$MANPATH}"
+MANPATH="$FLOX_ENV/share/man${MANPATH:+:$MANPATH}:"
```
Comment (ysndr) [inline pkgdb/src/buildenv/assets/etc/profile.d/0100_common-paths.sh:10]:
```suggestion
MANPATH="$FLOX_ENV/share/man:${MANPATH:+:$MANPATH}"
```

@mkenigs

- If MANPATH starts with `:` we now have `::` -> rule 3, the defaults are inserted in between, i.e. in front of MANPATH, but FLOXENV will take precedence in any case 
- If MANPATH ends with `:` we end with `:` -> rule 2, the defaults are appended (no change)
- IF MANPATH doe not start or end with `:`, FLOX_ENV:MANPATH replaces the defaults (no change)

**Review by mkenigs — APPROVED** [review]
