### PR TITLE
fix: return an error early if specified path does not contain `.flox`

### LINKED ISSUE #926: flox says it found a .flox when there isn't one
STR:
* be in a directory that does not contain a `.flox`
* `flox push`

Result:
image

Expected: 

Not to see statements that are not true

>Found a '.flox' directory, but were unable to locate an environment directory.
>Try deleting the '.flox' directory and reinitializing the environment.
>If you cloned this environment from a remote repository, verify that
`.flox/env/maifest.toml` is commited to the version control system.

### PR DESCRIPTION
**Pull request by ysndr**
fixes #926

### CODE REVIEW

File: cli/flox/src/utils/errors.rs [hunk 1]
```diff
@@ -22,7 +22,7 @@ pub fn format_error(err: &EnvironmentError2) -> String {
 
         // todo: enrich with a path?
         EnvironmentError2::EnvNotFound => formatdoc! {"
-            Found a '.flox' directory, but were unable to locate an environment directory.
+            Found a '.flox' directory, but was unable to locate an environment directory.
```
Comment (mkenigs) [inline cli/flox/src/utils/errors.rs:25]: nonblocking: we also throw this when `env.json` isn't found, so it would be nice to tweak the wording here and where we define `EnvNotFound`

**Review by mkenigs — APPROVED** [review]

File: cli/flox/src/utils/errors.rs (hunk 1 above)
Comment (ysndr) [reply cli/flox/src/utils/errors.rs:25]: Added a `EnvPointerNotFound` error to be more specific

**Review by mkenigs — APPROVED** [review]
