### PR TITLE
fix(activate): only detect python in `$FLOX_ENV`

### LINKED ISSUE #877: python3 xcode-select requirement
STR:
* be on a mac
* `sudo rm -rf /Library/Developer/CommandLineTools`
* `flox init`
* `flox activate`

Result: xcode-select prompt for python3
image

Expected: no xcode-select prompt

### PR DESCRIPTION
**Pull request by ysndr**
The profile.d script managing the python setup used to detect _any_ `python3` available on the `$PATH` which summons an xcode wizard on macos.
This PR changes the profile.d script to look for `python3` within `$FLOX_ENV/bin` explicitly.

fixes #877

### CODE REVIEW

**Review by zmitchell — CHANGES_REQUESTED** [review]
Can we add two test cases, one that checks that it correctly picks up the Python we do want, and one that checks that it _doesn't_ pick up the one we don't want?

File: pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh [hunk 1]
```diff
@@ -20,7 +20,7 @@ print( "{}.{}".format( sys.version_info[0], sys.version_info[1] ) )'
 fi
 
 # Only run if `pip' is in `PATH'
-if command -v pip > /dev/null 2> /dev/null; then
+if [[ -x "$FLOX_ENV/bin/pip3" ]]; then
   export PIP_CONFIG_FILE=$(@realpath@ --no-symlinks $FLOX_ENV/../../pip.ini)
```
Comment (ysndr) [inline pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh:24]: writing to that pip.ini file seems rather dangerous, considering that it will _replace_ the existing file if any.
Not sure if we should to fix this here but i can open an issue to track this at least.

Comment (ysndr) [reply pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh:24]: ah pip.init is written in the .flox dir

**Review by zmitchell — APPROVED** [review]
