### PR TITLE
fix: resolve priority conflicts between outputs of a package

### LINKED ISSUE #483: Env builder fails to handle conflicts in outputs
The lockfile [1] below currently fails to build using the new env-builder.

whats hapening here:

* flox is installing the `gcc-unwrapped` package (incorrectly instead of `gcc`, separate issue)
* `gcc-unwrapped` has **multiple outputs**
* **both the `out` and `lib` output contain `lib/libgcc_s.so`**
* the env builder is just seeing the conflict between the store paths

_The resolution is a separate issue and just unluckily played into this_

<details>
<summary>[1] Lockfile</summary>

```
{
  "lockfile-version": 0,
  "manifest": {
    "hook": { "script": "  echo \"Welcome to your flox environment\"" },
    "install": {
      "gcc": null
    },
    "registry": {
      "defaults": { "subtrees": null },
      "inputs": {
        "nixpkgs": {
          "from": {
            "owner": "NixOS",
            "ref": "release-23.05",
            "repo": "nixpkgs",
            "type": "github"
          },
          "subtrees": ["legacyPackages"]
        }
      },
      "priority": ["nixpkgs"]
    }
  },
  "packages": {
    "aarch64-linux": {
      "gcc": {
        "attr-path": ["legacyPackages", "aarch64-linux", "gcc-unwrapped"],
        "info": {
          "broken": false,
          "license": "GPL-3.0-or-later",
          "pname": "gcc",
          "unfree": false,
          "version": "12.2.0"
        },
        "input": {
          "attrs": {
            "lastModified": 1701053011,
            "narHash": "sha256-8QQ7rFbKFqgKgLoaXVJRh7Ik5LtI3pyBBCfOnNOGkF0=",
            "owner": "NixOS",
            "repo": "nixpkgs",
            "rev": "5b528f99f73c4fad127118a8c1126b5e003b01a9",
            "type": "github"
          },
          "fingerprint": "e1e8114f2d63213aae62896af91738ff24cc9ad8604ec59124d22367d82b07f3",
          "url": "github:NixOS/nixpkgs/5b528f99f73c4fad127118a8c1126b5e003b01a9"
        },
        "priority": 5
      }
    }
  },
  "registry": {
    "defaults": { "subtrees": null },
    "inputs": {
      "nixpkgs": {
        "from": {
          "lastModified": 1701053011,
          "narHash": "sha256-8QQ7rFbKFqgKgLoaXVJRh7Ik5LtI3pyBBCfOnNOGkF0=",
          "owner": "NixOS",
          "repo": "nixpkgs",
          "rev": "5b528f99f73c4fad127118a8c1126b5e003b01a9",
          "type": "github"
        },
        "subtrees": ["legacyPackages"]
      }
    },
    "priority": ["nixpkgs"]
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by ysndr**
fixes #483

* Sort outputs of the same derivation by an internal priority, I.e. the order in the 'outputs' list.
* bump pkgdb input

### CODE REVIEW

File: env-builder/src/buildenv.cc [hunk 1]
```diff
@@ -0,0 +1,246 @@
...
+        {
+          if ( e.errNo == ENOENT || e.errNo == ENOTDIR )
+            {
+              warn( "skipping dangling symlink '%s'", dstFile );
+              continue;
+            }
+          throw;
+        }
+
+      /* The files below are special-cased to that they don't show
```
Comment (aakropotkin) [inline env-builder/src/buildenv.cc:70]:
```suggestion
      /* The files below are special-cased so that they don't show
```

File: env-builder/src/buildenv.cc [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+      if ( hasSuffix( srcFile, "/propagated-build-inputs" )
+           || hasSuffix( srcFile, "/nix-support" )
+           || hasSuffix( srcFile, "/perllocal.pod" )
+           || hasSuffix( srcFile, "/info/dir" ) || hasSuffix( srcFile, "/log" )
+           || hasSuffix( srcFile, "/manifest.nix" )
+           || hasSuffix( srcFile, "/manifest.json" ) )
+        {
+          continue;
+        }
+
```
Comment (aakropotkin) [inline env-builder/src/buildenv.cc:85]:
```suggestion
```

Comment (aakropotkin) [reply env-builder/src/buildenv.cc:85]: non-blocking recommendation: Maybe add comment to explain what this block does.

File: env-builder/src/buildenv.cc [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+                  createLinks( state, srcFile, dstFile, priority );
+                  continue;
+                }
+            }
+          else if ( errno != ENOENT )
+            {
+              throw SysError( "getting status of '%1%'", dstFile );
+            }
+        }
+
```
Comment (aakropotkin) [inline env-builder/src/buildenv.cc:128]:
```suggestion
```

File: env-builder/src/buildenv.cc [hunk 4]
```diff
@@ -0,0 +1,246 @@
...
+      }
+    catch ( SysError & e )
+      {
+        if ( e.errNo != ENOENT && e.errNo != ENOTDIR ) { throw; }
+      }
+  };
+
+  /* Symlink to the packages that have been installed explicitly by the
+   * user. Process in priority order to reduce unnecessary
+   * symlink/unlink steps.
```
Comment (aakropotkin) [inline env-builder/src/buildenv.cc:200]:
```suggestion
  /* Symlink to the packages that have been installed explicitly by
   * the user.
   * Process in priority order to reduce unnecessary
    * symlink/unlink steps.
```

Comment (aakropotkin) [reply env-builder/src/buildenv.cc:200]: style

File: env-builder/src/buildenv.cc [hunk 5]
```diff
@@ -0,0 +1,246 @@
...
+    {
+      if ( pkg.active )
+        {
+          addPkg( pkg.path, pkg.priority + pkg.internalPriority );
+        }
+    }
+
+  /* Symlink to the packages that have been "propagated" by packages
+   * installed by the user (i.e., package X declares that it wants Y
+   * installed as well). We do these later because they have a lower
```
Comment (aakropotkin) [inline env-builder/src/buildenv.cc:229]:
```suggestion
   * installed as well).
   * We do these later because they have a lower
```

Comment (aakropotkin) [reply env-builder/src/buildenv.cc:229]: style

**Review by aakropotkin — APPROVED** [review]

**Comment by ysndr** [comment]
Todo: may have to take internalPrio into the file linking as well, otherwise an output might be able to over prio a package with higher priority.
Check if that is already "dealt with" by the sorting

**Comment by mkenigs** [comment]
> @mkenigs I moved some of the commonActivate stuff around slightly while dealing with merge conflicts. Just so you know, shouldn't be any functional change

👍 thanks for the heads up
