### PR TITLE
fix(git): test catching `push` authentication errors

### LINKED ISSUE #686: flox edit -r on purely remote environment fails
STR:
* create and push a remote env (ghudgins/cli for me)
* `flox edit -r ghudgins/cli` (that remote env)
* add something to the manifest that's valid

Result: error / hanging
Expected: success!

image

### PR DESCRIPTION
**Pull request by ysndr**
* Add another error detection for failed authentication with git remotes (i.e. floxhub)
* Improve error reporting

closes #686
(cherry picked from commit 784b61704d028231d0d75a6eaa1e11850d85148c)

### CODE REVIEW

File: cli/flox-rust-sdk/src/models/floxmetav2/mod.rs [hunk 1]
```diff
@@ -162,15 +163,24 @@ pub fn floxmeta_git_options(floxhub_host: &str, floxhub_token: Option<&str>) ->
...
+        token
+    } else {
+        debug!("no floxhub token configured");
+        ""
+    };
+
+    // Set authentication with the floxhub token using an inline credential helper.
+    // The credential helper should help avoinding a leak of the token in the process list.
+    //
+    // If no token is provided, we still set the credential helper
```
Comment (mkenigs) [inline cli/flox-rust-sdk/src/models/floxmetav2/mod.rs:177]: nonblocking
```suggestion
    // If no token is provided, we still set the credential helper and pass an empty string as password
```

**Review by mkenigs — CHANGES_REQUESTED** [review]
question blocking: should this have a test?

**Comment by ysndr** [comment]
This is still relevant even though #686 was closed by the other PR
This one adds the same error handling to other fig operations and adds tests

**Comment by ghudgins** [comment]
tested this on the branch...saw an extra error that looked a bit confusing after I said `n` to continue editing

image

**Comment by ysndr** [comment]
did you run `just flox`?
That error looks a lot like a Justfile error

**Comment by ghudgins** [comment]
ah yes, I did. then LGTM

**Review by mkenigs — APPROVED** [review]
