### PR TITLE
fix: Don't warn about non-existent config when creating it

### LINKED ISSUE #181: Unclear if metric disable is working (output does not leave me convinced)
**Describe the bug:**

When attempting to opt out of metric collection, I see an error or warning, so I'm not sure if it worked.

Fresh install of flox (never been on this system before)

**Steps to reproduce:**

```
floxautomations@msn-aarch64-darwin-01 ~ % flox list
Updating "/Users/floxautomations/.config/flox/gitconfig"
flox collects basic usage metrics in order to improve the user experience.

    flox includes a record of the subcommand invoked along with a unique token.
    It does not collect any personal information.

    Example metric for this invocation:

    {
      "empty_flags": [],
      "flox_version": "0.2.5-r553",
      "os": null,
      "os_family": "Mac OS",
      "os_family_release": "22.6.0",
      "os_version": null,
      "subcommand": "[subcommand]",
      "timestamp": "2023-07-27 22:30:51.052353 +00:00:00",
      "uuid": "58f6d805-02fd-467d-bf73-6b40426bf90b"
    }

    The collection of metrics can be disabled in the following ways:

      environment: FLOX_DISABLE_METRICS=true
        user-wide: flox config --set-bool disable_metrics true
      system-wide: update /etc/flox.toml as described in flox(1)


Updating "/Users/floxautomations/.config/flox/nix.conf"
warning: remote HEAD refers to nonexistent ref, unable to checkout

ERROR: environment 'local/aarch64-darwin.default' not  found for system 'aarch64-darwin'

floxautomations@msn-aarch64-darwin-01 ~ %  flox config --set-bool disable_metrics true
No existing user config file found in "/Users/floxautomations/.config/flox/flox.toml"
floxautomations@msn-aarch64-darwin-01 ~ %
```

Result: 
```
floxautomations@msn-aarch64-darwin-01 ~ %  flox config --set-bool disable_metrics true
No existing user config file found in "/Users/floxautomations/.config/flox/flox.toml"
floxautomations@msn-aarch64-darwin-01 ~ %
```
I'm unclear if `No existing user config file found in "/Users/floxautomations/.config/flox/flox.toml"` is important, or a debug statement, or something I was supposed to have done. 

Expected: 

no output and exit 0.

**Screenshots/terminal output (if relevant):**

### PR DESCRIPTION
**Pull request by nicklewis**
This message doesn't represent anything the user needs to be aware of or
take action based on, so it can be logged more quietly.

Fixes #181

### CODE REVIEW

File: crates/flox/src/config/mod.rs [hunk 1]
```diff
@@ -308,7 +308,7 @@ impl Config {
         let config_file_contents = match fs::read_to_string(&config_file_path) {
             Ok(s) => Ok(Some(s)),
             Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
-                warn!(
+                debug!(
                     "No existing user config file found in {:?}",
```
Comment (ysndr) [inline crates/flox/src/config/mod.rs:312]: Change this notice to say we are creating a config file?

**Review by ysndr — APPROVED** [review]

File: crates/flox/src/config/mod.rs (hunk 1 above)
Comment (nicklewis) [reply crates/flox/src/config/mod.rs:312]: I thought about that, but I think the user doesn't really care much that the file is being created. We don't print anything if the file already exists, so this makes it consistent.

Comment (ysndr) [reply crates/flox/src/config/mod.rs:312]: no i mean additionally to making it debug.
just when we read a debug log we know its being created and dont have to remember

Comment (nicklewis) [reply crates/flox/src/config/mod.rs]: Ah got it. Updated.

**Review by tomberek — APPROVED** [review]
