### PR TITLE
fix(uninstall): Correct package uninstallation with dotted attr_path

### LINKED ISSUE #1714: confusing uninstall messaging for dotted attr_paths
**Describe the bug:**
When installing a package with a dotted path, and then try to uninstall the same, you get an error saying that it is not installed in the environment.

**Steps to reproduce:**
1. Install a dotted package like `python311Pakcages.tensorflow-bin`
2. Try to uninstall the same.

Result:
You get the error saying that the package is not installed.

Expected:
The package is uninstalled correctly.

**Screenshots/terminal output (if relevant):**
```
> flox install python311Packages.tensorflow-bin
✅ 'tensorflow-bin' installed to environment 'foo'

> flox uninstall python311Packages.tensorflow-bin
❌ ERROR: Failed to modify manifest.

couldn't uninstall 'python311Packages.tensorflow-bin', wasn't previously installed

> flox list
tensorflow-bin: python311Packages.tensorflow-bin (python3.11-tensorflow-2.16.1)

> flox uninstall tensorflow-bin
🗑️  'tensorflow-bin' uninstalled from environment 'foo'
```

**flox Version (run `flox --version` if possible):**

v1.1.0

### PR DESCRIPTION
**Pull request by tanjadev**
This resolves the issue causing confusing messages when uninstalling packages with a dotted attr_path (e.g., foo.bar). The package name is now correctly parsed, allowing such packages to be uninstalled from the environment.

fixes #1714

### CODE REVIEW

**Review by ghudgins — APPROVED** [review]
functionality LGTM. (not a code review)

File: cli/flox-rust-sdk/src/models/manifest.rs [hunk 1]
```diff
@@ -1228,11 +1228,17 @@ pub fn remove_packages(
 
     for pkg in pkgs {
         debug!("checking for presence of package '{pkg}'");
-        if !installs_table.contains_key(pkg) {
+
+        // Get package id from the nested key or keep the package name as the id
+        let pkg_id = CatalogPackage::from_str(pkg)
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/models/manifest.rs:1233]: I don't think this logic is quite right. What we want is (in this order):
```
if str == an existing install_id
    use that id
else if str == the pkg-path for an existing pkg
    use the id for that pkg
else
    error
```
What we have here is:
```
if str can be parsed as a pkg
    use the inferred id of that pkg
else
    use str as the id
```

Without checking (not at a computer at the moment) I think this would miss `flox uninstall cargo` for `mycargo.pkg-path = "cargo"` since it would parse `cargo` into an inferred install id of `cargo` rather than looking up "the id of the package whose pkg-path is `cargo`".

Comment (zmitchell) [reply cli/flox-rust-sdk/src/models/manifest.rs:1233]: It would be good to have a test case for that scenario. The ticket is asking us to support uninstalling via pkg-path, not just an install id that has a dot in it.

**Review by zmitchell — CHANGES_REQUESTED** [review]

**Comment by brendaneamon** [comment]
> With the following chunk in the manifest:
> 
> ```
> tv1 = {pkg-path = "python311Packages.torchvision-bin", systems=["aarch64-darwin", "x86_64-darwin"],  pkg-group="darwin"}
> tv2 = {pkg-path = "python311Packages.torchvision-bin", systems=["aarch64-linux", "x86_64-linux"],  pkg-group="linux"}
> ```
> 
> I get a failure for `flox uninstall python311Packages.torchvision-bin`. This is the case I had in mind for the `XYZ is ambiguous, please use the install-id, one of [ tv1, tv2 ]`. Or something like that.

@billlevine, @tanjadev, if I'm not mistaken, this is related to the following issue: https://github.com/flox/flox/issues/1512

File: cli/flox-rust-sdk/src/models/manifest.rs [hunk 2]
```diff
@@ -897,8 +897,7 @@ pub enum TomlEditError {
     /// The `[install]` table was missing entirely
     #[error("'install' table not found")]
     MissingInstallTable,
-    /// Tried to uninstall a package that wasn't installed
-    #[error("couldn't uninstall '{0}', wasn't previously installed")]
+    #[error("couldn't find package '{0}' in the manifest")]
```
Comment (billlevine) [inline cli/flox-rust-sdk/src/models/manifest.rs:900]: nb: Since the _item_ to remove could be a package or an install id, would it be better to simplify this message as `couldn't find '{0}' in the manifest` ?

**Review by billlevine — APPROVED** [review]

File: cli/flox-rust-sdk/src/models/manifest.rs (hunk 2 above)
Comment (zmitchell) [reply cli/flox-rust-sdk/src/models/manifest.rs:900]: I'd say yes

File: cli/flox-rust-sdk/src/models/manifest.rs (hunk 1 above)
Comment (tanjadev) [reply cli/flox-rust-sdk/src/models/manifest.rs]: Yep, that was due to my initial misinterpretation of the ACs 🤦‍♀️ Now the logic should match what you've described. I've added some unit tests that cover different cases (as discussed with @ysndr).

File: cli/flox-rust-sdk/src/models/manifest.rs (hunk 2 above)
Comment (tanjadev) [reply cli/flox-rust-sdk/src/models/manifest.rs:900]: Good point, the term "package" can be a bit ambiguous here.

In fact, now it's back to only being the install id, as we extract them in the Core Environment before calling the remove function. Initially, it was designed to handle both package and install id, but after feedback, I moved the handling to the Core Environment. I've updated the wording in the code and logs to "install id" to make it clearer.

**Comment by tanjadev** [comment]
This one is ready for another round of review. I've changed a bit of wording and added some unit tests covering the following cases: 

- Return the install ID if it matches the user input.
- Return the install ID if a pkg-path matches the user input.
- Ensure that the install ID takes precedence over pkg-path when both are present, resulting in the deletion of the corresponding package.
- Throw an error if multiple pkg-paths match the user input.
- Throw an error if no install ID or pkg-path matches the user input.

**Comment by zmitchell** [comment]
I'll give a look after the service management meeting 👍

File: cli/flox-rust-sdk/src/models/environment/core_environment.rs [hunk 3]
```diff
@@ -420,6 +424,45 @@ impl CoreEnvironment<ReadOnly> {
         })
     }
 
+    fn get_install_ids_to_uninstall(
+        manifest: &TypedManifest,
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/models/environment/core_environment.rs:428]: Note to self: this can take a `&TypedManifestCatalog` instead since we're about to no longer allow locking v0  (`pkgdb`) manifests, which removes the need for `if let ...`

File: cli/flox-rust-sdk/src/models/environment/core_environment.rs [hunk 4]
```diff
@@ -1196,6 +1239,14 @@ pub enum CoreEnvironmentError {
     OpenManifest(#[source] std::io::Error),
     #[error("could not write manifest")]
     UpdateManifest(#[source] std::io::Error),
+    /// Tried to uninstall a package that wasn't installed
+    #[error("couldn't uninstall '{0}', wasn't previously installed")]
+    PackageNotFound(String),
+    // Multiple packages match user input, must specify install_id
+    #[error(
+        "multiple packages match '{0}', please specify an install id from possible matches: {1:?}"
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/models/environment/core_environment.rs:1247]: Note to self: May want to tweak how the matches are displayed by doing a `.join(", ")` into a `String` instead

**Review by zmitchell — APPROVED** [review]
