### PR TITLE
fix: improve download failure error with actual nix copy stderr

### LINKED ISSUE #4054: Improve download failure error
Report in https://flox-dev.slack.com/archives/C0AFSQ6BFEW/p1772551408453059

We should pass some more context through with this error
```
> flox activate -- true
✘ ERROR: Failed to build environment:

Couldn't download package '{package}' for unknown reason
```

Looks like we just need to address this TODO
https://github.com/flox/flox/blob/e285bb2a8b4cb3454a5a3e97e98ad5672f5d32d0/cli/flox-rust-sdk/src/providers/buildenv.rs#L108-L111

### PR DESCRIPTION
**Pull request by tonky**
## Disclaimer

Hi, i just wanted to improve a couple of things(along with 'bpaf' fix for #3411), will gladly improve/iterate on this PR. This wasn't hand-written, but resulting code and tests looks good to me.

## Summary

- Changes `BuildPublishedPackage` error from "unknown reason" to include actual `nix copy` stderr output
- Collects errors from each failed download location attempt
- Updates test to assert the error contains meaningful reason text

Closes #4054

## Test plan

- [x] Existing test `nixpkgs_published_pkg_cache_download_failure` updated and passes
- [x] `cargo check` passes

### CODE REVIEW

File: cli/flox-rust-sdk/src/providers/buildenv.rs [hunk 1]
```diff
@@ -1635,10 +1686,18 @@ mod realise_nixpkgs_tests {
...
+        assert_eq!(err.to_string(), indoc! {r#"
+            Couldn't download package 'hello' from the following locations
+
+            daemon:
+              don't know how to build these paths:
+                /nix/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-invalid
+              error: path '/nix/store/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-invalid' is required, but there is no substituter that can build it
+
+            base catalog:
+              encountered an error interpreting the lockfile: Locked package 'hello' is a base catalog package, but the locked url 'github:super/custom/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' does not start with the expected prefix 'https://github.com/flox/nixpkgs?rev='"#});
```
Comment (mkenigs) [inline cli/flox-rust-sdk/src/providers/buildenv.rs:1700]: It's hard to tell from here that this bubbles up correctly through errors.rs

**Comment by dcarley** [comment]
@tonky thanks for the contribution and sorry for the delay in responding to this. I made some small tweaks and got an additional internal review. Just waiting for CI.
