### PR TITLE
fix: do not relay stdout/err coming from builder

### LINKED ISSUE #3118: feat: resume displaying output from `flox build clean`
The `flox build clean` command currently suppresses output from the resulting `make` invocation. Presumably we did this because the various "clean" targets were noisy, always printing out the files & directories deleted in each instance.

I've since updated the clean targets to have configurable verbosity by adding the `$(_V_)` decorator to all of the `rm` invocations, so it's once again safe to resume printing this output when invoked as `flox -v build clean`.

Following is an example of the output currently seen when invoking `flox -v build clean`, and what should be displayed in this case:
```
flox [limeytexan/default] Michaels-MBP% flox build -vv clean
2025-05-28T10:07:41.823343Z DEBUG flox::config: reading raw config (initialized: false, reload: false)
2025-05-28T10:07:41.823372Z DEBUG flox::config: `$FLOX_CONFIG_DIR` not set, using "/Users/brantley/.config/flox/"
2025-05-28T10:07:41.823781Z DEBUG flox: set _FLOX_PKGDB_VERBOSITY=2
2025-05-28T10:07:41.824593Z DEBUG flox::config: reading raw config (initialized: true, reload: false)
2025-05-28T10:07:41.824845Z DEBUG flox::commands: Skipping update check in development mode
2025-05-28T10:07:41.824931Z DEBUG flox::commands: Metrics collection disabled
2025-05-28T10:07:41.824971Z DEBUG flox::utils::init::catalog_client: using catalog client with url: https://api.flox.dev
2025-05-28T10:07:41.827328Z DEBUG flox::commands: features enabled, build=true, publish=true, upload=false
2025-05-28T10:07:41.827353Z DEBUG flox::utils::metrics: No metrics client setup, skipping record
2025-05-28T10:07:41.827418Z DEBUG flox_rust_sdk::models::environment: looking for .flox: starting_path=/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR/.flox
2025-05-28T10:07:41.827497Z DEBUG flox_rust_sdk::models::environment: .flox found: path=/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR/.flox
2025-05-28T10:07:41.827518Z DEBUG flox_rust_sdk::models::environment: detected concrete environment type: path
2025-05-28T10:07:42.171423Z DEBUG build::clean: flox::commands::build: found manifest_build package=foo
2025-05-28T10:07:42.171443Z DEBUG build::clean: flox::commands::build: found manifest_build package=foo-bar
2025-05-28T10:07:42.171448Z DEBUG build::clean: flox::commands::build: found nix expression package=curl
2025-05-28T10:07:42.171451Z DEBUG build::clean: flox::commands::build: found nix expression package=hello
2025-05-28T10:07:42.171455Z DEBUG build::clean: flox::commands::build: found nix expression package=neovim
2025-05-28T10:07:42.171470Z DEBUG build::clean: flox_rust_sdk::providers::build: running manifest clean target command=env -u MAKEFLAGS /nix/store/cnkfqpa3kyi3mgk0yd8lqbrdysq7j38q-gnumake-4.4.1/bin/make --file /nix/store/7ccnc0l82bbqpc0sjahz844g7mrsm1zy-package-builder-1.0.0/libexec/flox-build.mk --directory /private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR 'BUILDTIME_NIXPKGS_URL=github:flox/nixpkgs/698214a32beb4f4c8e3942372c694f40848b360d?narHash=sha256-hw63HnwnqU3ZQfsMclLhMvOezpM7RSB0dMAtD5/sOiw=' FLOX_ENV=/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR/.flox/run/aarch64-darwin.tmp.6UyrBaUNYR.dev NIX_EXPRESSION_DIR=/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR/.flox/pkgs clean/foo clean/foo-bar clean/curl clean/hello clean/neovim
✨ Clean completed successfully
2025-05-28T10:07:42.791026Z DEBUG flox::utils::metrics: No metrics client setup, skipping flush
flox [limeytexan/default] Michaels-MBP% env -u MAKEFLAGS /nix/store/cnkfqpa3kyi3mgk0yd8lqbrdysq7j38q-gnumake-4.4.1/bin/make --file /nix/store/7ccnc0l82bbqpc0sjahz844g7mrsm1zy-package-builder-1.0.0/libexec/flox-build.mk --directory /private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR 'BUILDTIME_NIXPKGS_URL=github:flox/nixpkgs/698214a32beb4f4c8e3942372c694f40848b360d?narHash=sha256-hw63HnwnqU3ZQfsMclLhMvOezpM7RSB0dMAtD5/sOiw=' FLOX_ENV=/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR/.flox/run/aarch64-darwin.tmp.6UyrBaUNYR.dev NIX_EXPRESSION_DIR=/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR/.flox/pkgs clean/foo clean/foo-bar clean/curl clean/hello clean/neovim 
make: Entering directory '/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR'
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-foo-buildCache
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-foo
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-foo-log
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -rf /var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T//05022d14/foo
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-foo-bar
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-foo-bar-log
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -rf /var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T//05022d14/foo-bar
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl-log
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl-bin
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl-dev
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl-devdoc
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl-man
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-curl-out
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -rf /var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T//05022d14/curl
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-hello
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-hello-log
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-hello-out
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -rf /var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T//05022d14/hello
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-neovim
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-neovim-log
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -f result-neovim-out
/nix/store/4idwmksk4s5bdmzl1sz1z17bj0yfqgkj-coreutils-9.6/bin/rm -rf /var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T//05022d14/neovim
make: Leaving directory '/private/var/folders/0n/y7q2hx2168dcjr6nn78cgk1m0000gn/T/tmp.6UyrBaUNYR'
flox [limeytexan/default] Michaels-MBP% 
```

### PR DESCRIPTION
**Pull request by limeytexan**
## Proposed Changes

Unlike Nix builds which solely write to stderr, the manifest builder emits lines to both stdout and stderr, which presents the possibility of getting the ordering wrong when printing those lines to the tty. We wrote `t3` specifically to address this issue while at the same time providing color highlighting and timestamping, but then undid all that by again reading and writing each line of output from flox, thereby re-introducing the possibility that lines can come out of order.

This patch updates `FloxBuildMk::{clean,build}` to inherit stdio rather than relaying output and streaming possibly out of order at the CLI level. For the use in tests, or other deliberate use where the output should be suppressed and collected instead, `FloxBuildMk::new_with_buffers`, was added to provide `&mut String` references that will be filled with the the output instead.

Closes #3118 

## Release Notes

* Fixed bug that can cause lines of manifest build output to appear out of order on the terminal

### CODE REVIEW

**Comment by limeytexan** [comment]
Background discussion: https://flox-dev.slack.com/archives/C074WPYRJUB/p1752083645438319

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 1]
```diff
@@ -153,6 +121,10 @@ pub struct FloxBuildMk<'args> {
     base_dir: &'args Path,
     expression_dir: &'args Path,
     built_environments: &'args BuildEnvOutputs,
+
+    //
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: nit: remove empty comment and blank line

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 2]
```diff
@@ -264,64 +258,53 @@ impl ManifestBuilder for FloxBuildMk<'_> {
         // this since it's also passed for `flox activate`
         command.env(FLOX_RUNTIME_DIR_VAR, self.runtime_dir);
 
-        command.stdout(Stdio::piped());
-        command.stderr(Stdio::piped());
+        if self.stdout_buffer.is_some() {
+            command.stdout(Stdio::piped());
+        } else {
+            command.stdout(Stdio::inherit());
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: Inherit is the default, so you don't need the `else` side of this condition.

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 3]
```diff
@@ -264,64 +258,53 @@ impl ManifestBuilder for FloxBuildMk<'_> {
...
+        }
+
+        if self.stderr_buffer.is_some() {
+            command.stderr(Stdio::piped());
+        } else {
+            command.stderr(Stdio::inherit());
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: Same thing re: inherit being the default

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 4]
```diff
@@ -264,64 +258,53 @@ impl ManifestBuilder for FloxBuildMk<'_> {
...
         let mut child = command
             .spawn()
             .map_err(ManifestBuilderError::CallBuilderError)?;
 
-        let (sender, receiver) = std::sync::mpsc::channel();
-        let stdout_sender = sender.clone();
-        let stderr_sender = sender.clone();
-        let command_status_sender = sender;
+        if let Some(buffer) = self.stdout_buffer.as_mut() {
+            let stdout = child.stdout.take().expect("set when buffer present");
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: I'm not sure how to interpret the error message here, could you provide a clearer message?

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 5]
```diff
@@ -264,64 +258,53 @@ impl ManifestBuilder for FloxBuildMk<'_> {
...
+            let tap = stdout.tap_lines(|_| {});
+            std::mem::swap(*buffer, &mut tap.wait());
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: Regarding timing, the way I read this is that we tap and collect `stdout` until the reader thread has exited. You do that before we ever tap the `stderr` stream, so by the time you get there the reader thread should have exited. Doesn't that mean that we completely throw away `stderr` because the process we're reading from has exited already by the time we go to tap `stderr`?

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 6]
```diff
@@ -364,48 +347,43 @@ impl ManifestBuilder for FloxBuildMk<'_> {
...
         debug!(command=%command.display(), "running manifest clean target");
 
-        let output = command
-            .output()
-            .map_err(ManifestBuilderError::CallBuilderError)?;
-        let status = output.status;
+        if self.stdout_buffer.is_some() {
+            command.stdout(Stdio::piped());
+        } else {
+            command.stdout(Stdio::inherit());
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: Same thing re: inherit being the default

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 7]
```diff
@@ -364,48 +347,43 @@ impl ManifestBuilder for FloxBuildMk<'_> {
...
+        }
 
-        if !status.success() {
-            let stderr = String::from_utf8_lossy(&output.stderr).to_string();
-            let stdout = String::from_utf8_lossy(&output.stdout).to_string();
+        if self.stderr_buffer.is_some() {
+            command.stderr(Stdio::piped());
+        } else {
+            command.stderr(Stdio::inherit());
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: Same thing re: inherit being the default

File: cli/flox-rust-sdk/src/providers/build.rs [hunk 8]
```diff
@@ -364,48 +347,43 @@ impl ManifestBuilder for FloxBuildMk<'_> {
...
 
-            return Err(ManifestBuilderError::RunClean {
-                stdout,
-                stderr,
-                status,
-            });
+        if let Some(buffer) = self.stdout_buffer.as_mut() {
+            let stdout = child.stdout.take().expect("set when buffer present");
+            let tap = stdout.tap_lines(|_| {});
+            std::mem::swap(*buffer, &mut tap.wait());
```
Comment (zmitchell) [inline cli/flox-rust-sdk/src/providers/build.rs]: Same comment here re: waiting for `stdout` before tapping `stderr`.

File: cli/flox/src/commands/build.rs [hunk 9]
```diff
@@ -203,44 +202,30 @@ impl Build {
...
-                Output::Failure(status) => {
-                    bail!("Build failed with status: {status}");
-                },
-            }
+                links_to_print.join(", ")
+            ));
+        } else {
+            message::created(format!(
+                "Build completed successfully. Output created: {}",
+                links_to_print[0]
```
Comment (zmitchell) [inline cli/flox/src/commands/build.rs]: I know this is just refactoring the existing code, but we've only checked the `links_to_print` has more than one element at this point, and this code assumes that `!(len > 1)` means `1` when it could also be `0`. That would panic, so we should use a `.get` here instead and handle the empty case.

File: cli/flox-rust-sdk/src/providers/build.rs (hunk 5 above)
Comment (ysndr) [reply cli/flox-rust-sdk/src/providers/build.rs]: I you're right generally, that if we wait for termination of one pipe we defer even starting to read the other.
This works in the tests we have, likely because of the pipe buffer being large enough to soak up all the not yet tapped output on stderr.
I changed this to tap both pipes first and _then_ wait for them to complete which should avoid this on larger outputs.
